language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-22.0.0

    # The SDK version used to compile your project
    - android-22

    # Extra android repos
    - extra-android-m2repository
